#!/bin/bash
###############################################################################
# Eklipsed Craft
# Minecraft Beta but it runs faster and is made using C (very based)
#
# WARNING: This is free and I don't own Minecraft, this is just for fun okay
#
# This file configures make for you
###############################################################################

target=rel
if [[ "$#" -eq 1 ]]; then
	case $(echo "$1" | tr '[:upper:]' '[:lower:]') in
		"release" | "r" | "rel")
			target=rel
			;;
		"debug" | "dbg" | "d")
			target=dbg
			;;
		"--delete-makefile")
			rm -f Makefile
			exit 0
			;;
		*)
			echo "\
usage:
./configure.sh [options] [mode]
options:
	--delete-makefile
modes:
	release -- for release mode
	debug -- for debug mode"
			exit 0
			;;
	esac
fi

echo "\
###############################################################################
# GENERATED BY CONFIGURE
#
# This file is just a head to include compile.mk
###############################################################################

# Variables
TARGET    := $target
BUILD_DIR := build_$target
PROG      = build_$target/csi
SRC_DIR   := src

include build.mk
" > Makefile

