###############################################################################
# GENERATED BY CONFIGURE
#
# This file is just a head to include compile.mk
###############################################################################

# Variables
TARGET    := dbg
BUILD_DIR := build_dbg
PROG      = build_dbg/csi
SRC_DIR   := src

include build.mk

