#!/bin/bash

# First test to see even if the header can be used freestanding (on your host machine)
echo "\
#define CSCRIPT_IMPL
#include \"cscript.h\"

int main(int argc, char **argv) {
	// Do more cscript things here
	return 0;
}
" > tmp.c
gcc -std=c11 -ffreestanding -pedantic -Wall -Werror tmp.c -o tmp.out
if [[ "$?" -ne 0 ]]; then
	echo "Can't compile with freestanding."
	exit
fi
rm -f tmp.c tmp.out

# Now compile and run tester.c
gcc -std=c11 -pedantic -Wall -Werror tester.c -o tester
if [[ "$?" -ne 0 ]]; then
	echo "Couldn't compile the tester."
	exit
fi
./tester

