extern fn print_i32(val: i32);
extern fn input_i32() -> i32;

fn print_until(a: u64, b: i8) {
    a += b;
    for x: u64 in (0..a) {
        print_i32(x);
    }
}

fn main() -> b8 {
    print_until(input_i32(), 4);
    return true;
}

//
//let TEST: i32 = "";
//
//fn cpy<T>(from: &[T], to: &[T]) {
//    let len = min(lenof(from), lenof(to));
//    for let i = 0..len { to[i] = from[i]; }
//}
//
//static fn printn(n: i32) -> u0 {
//	let i = new i32{5};
//	while i < n {
//		print_int(i);
//		i = i + 1;
//	}
//}
//
//fn main() -> i32 {
//	let arr: [i32] = [0, 1, 2, 3, 4];
//	arr[2] = input_int();
//	printn(arr[2]);
//	return 0;
//}

// [0, 0, 0, 0, 0]
// [i32; 5]
// 0
// i32{0}
// struct_s{}
// struct_s{
//     x: 5,
//     y: 1,
// }

