#include <assert.h>
#include <limits.h>
#include <stdint.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include "lexer.h"

const char *tokty_to_str(const tokty_t ty) {
	switch (ty) {
#define enumdef(e) case e: return #e;
tokty_def
#undef enumdef
	default: return "ERR";
	}
}

char *_keywords[tok_max_keywords];

keyword_t *_words;
size_t _nwords;

void add_keyword(const char *keyword, tokty_t ty) {
	keyword_t kw = (keyword_t){
		.hash = ident_hash(keyword, strlen(keyword)),
		.len = strlen(keyword),
		.psl = 0,
		.str = keyword,
		.ty = ty,
	};

	int i = kw.hash % _nwords;
	while (_words[i].str) {

		if (kw.psl > _words[i].psl) {
			// swap
			const keyword_t tmp = _words[i];
			_words[i] = kw;
			kw = tmp;
		}

		i = (i + 1) % _nwords;
		kw.psl++;
	}

	_words[i] = kw;
}

// Returns number of collisions
size_t gen_hashmap(size_t len) {
	assert(__builtin_popcount(len) == 1); // Make sure len is power of 2
	_nwords = len;
	if (_words) free(_words);
	_words = calloc(sizeof(*_words), _nwords);
	
	for (size_t i = 0; i < tok_max_keywords; i++) {
		add_keyword(_keywords[i], i);
	}

	size_t cols = 0;
	for (size_t i = 0; i < _nwords; i++) {
		cols += _words[i].psl > 0;
	}

	return cols;
}

int main(int argc, char **argv) {
	if (argc != 2) {
		printf("hashmapgen.c [hashmap variable identifier]\n");
		return 1;
	}

	// setup _keywords array
	for (int i = 0; i < tok_max_keywords; i++) {
		const char *enumstr = tokty_to_str((tokty_t)i);
		_keywords[i] = malloc(strlen(enumstr) - 4);
		strcpy(_keywords[i], enumstr + 4);
	}

	size_t ncols = gen_hashmap(128);
	printf("// Auto generated by hashmapgen.c\n");
	printf("static const keyword_t %s[%zu] = {\n", argv[1], _nwords);
	for (size_t i = 0; i < _nwords; i++) {
		printf(
			"    (keyword_t){ .hash = %u, .len = %zu, .psl = %d, .ty = ",
			_words[i].hash,
			_words[i].len,
			_words[i].psl
		);
		if (_words[i].str) printf("tok_%s", _keywords[_words[i].ty]);
		else printf("tok_error");
		printf(", .str = ");
		if (_words[i].str) printf("\"%s\"", _words[i].str);
		else printf("NULL");
		printf(" },\n");
	}
	printf("};\n");
	printf("num cols: %zu\n", ncols);
	free(_words);

	for (int i = 0; i < tok_max_keywords; i++) {
		free(_keywords[i]);
	}

	return 0;
}

