#include <stdio.h>
#include <string.h>

#include "lexer.h"

static const char *keyword_strs[tok_num_keywords] = {
    [tok_extern]    = "extern",
    [tok_static]    = "static",
    [tok_fn]        = "fn",
    [tok_let]       = "let",
    [tok_if]        = "if",
    [tok_as]        = "as",
    [tok_else]      = "else",
    [tok_in]        = "in",
    [tok_for]       = "for",
    [tok_while]     = "while",
    [tok_new]       = "new",
    [tok_return]    = "return",
    [tok_break]     = "break",
    [tok_continue]  = "continue",
    [tok_typedef]   = "typedef",
    [tok_null]      = "null",
    [tok_switch]    = "switch",
    [tok_case]      = "case",
    [tok_default]   = "default",
    [tok_const]     = "const",
    [tok_do]        = "do",
    [tok_enum]      = "enum",
    [tok_struct]    = "struct",
    [tok_true]      = "true",
    [tok_false]     = "false",
    [tok_sizeof]    = "sizeof",
    [tok_lenof]     = "lenof",
    [tok_i8]        = "i8",
    [tok_i16]       = "i16",
    [tok_i32]       = "i32",
    [tok_i64]       = "i64",
    [tok_u8]        = "u8",
    [tok_u16]       = "u16",
    [tok_u32]       = "u32",
    [tok_u64]       = "u64",
    [tok_f32]       = "f32",
    [tok_f64]       = "f64",
    [tok_c8]        = "c8",
    [tok_c16]       = "c16",
    [tok_c32]       = "c32",
    [tok_b8]        = "b8",
    [tok_u0]        = "u0",
};

#define LEX_KEYWORDMAP_SIZE 83

static lex_keyword_t keywords[LEX_KEYWORDMAP_SIZE];

static void keywords_init(void) {
    for (uint32_t i = 0; i < LEX_KEYWORDMAP_SIZE; i++) {
        keywords[i] = (lex_keyword_t){
            .type = tok_eof,
#ifdef INC_STR
            .str = (strview_t){.str = NULL, .len = 0},
#endif
            .hash = 0,
            .psl = 0,
        };
    }
}

static void keywords_add(strview_t str, lex_token_type_t type) {
    lex_keyword_t kw = {
#ifdef INC_STR
        .str = str,
#endif
        .psl = 0,
        .type = type,
        .hash = strview_hash(str),
    };
    uint32_t i = kw.hash % LEX_KEYWORDMAP_SIZE;

#ifdef INC_STR
    while (keywords[i].str.str) {
#else
    while (keywords[i].type != tok_eof) {
#endif
        if (kw.psl > keywords[i].psl) {
            lex_keyword_t tmp = keywords[i];
            keywords[i] = kw;
            kw = tmp;
        }

        kw.psl++;
        i = (i + 1) % LEX_KEYWORDMAP_SIZE;
    }

    keywords[i] = kw;
}

#define X(ENUM) case ENUM: return #ENUM;
static const char *type_to_str(lex_token_type_t type) {
    switch (type) {
    LEX_TOKENS_KEYWORDS
    default: return "tok_eof";
    }
}
#undef X

static void keywords_write(const char *header_guard, int ncollisions, int max_psl, FILE *file) {
    fprintf(file, "#ifndef %s\n", header_guard);
    fprintf(file, "#define %s\n", header_guard);
    fprintf(file, "\n");
    fprintf(file, "#include <stddef.h>\n");
    fprintf(file, "\n");
    fprintf(file, "#include \"lexer.h\"\n");
    fprintf(file, "\n");
    fprintf(file, "#define KEYWORDMAP_SIZE %u\n", LEX_KEYWORDMAP_SIZE);
    fprintf(file, "\n");
    fprintf(file, "// \n");
    fprintf(file, "// Auto generated by keywordgen.\n");
    fprintf(file, "// This robinhood hashmap is used by the lexer to identify keywords.\n");
    fprintf(file, "// # of collisions: %d, max_psl: %d\n", ncollisions, max_psl);
    fprintf(file, "// capacity: %d/%d\n", tok_num_keywords, LEX_KEYWORDMAP_SIZE);
    fprintf(file, "// \n");
    fprintf(file, "static const lex_keyword_t keywordmap[KEYWORDMAP_SIZE] = {\n");
    for (int i = 0; i < LEX_KEYWORDMAP_SIZE; i++) {
        fprintf(file, "    (lex_keyword_t){\n");
#ifdef INC_STR
        fprintf(file, "        .str = (strview_t){\n");
        if (keywords[i].str.str) {
            fprintf(file, "            .str = \"%s\",\n", keywords[i].str.str);
        } else {
            fprintf(file, "            .str = NULL,\n");
        }
        fprintf(file, "            .len = %zu,\n", keywords[i].str.len);
        fprintf(file, "        },\n");
#endif
        fprintf(file, "        .type = %s,\n", type_to_str(keywords[i].type));
        fprintf(file, "        .hash = %u,\n", keywords[i].hash);
        fprintf(file, "        .psl = %u,\n", keywords[i].psl);
        fprintf(file, "    },\n");
    }
    fprintf(file, "};\n");
    fprintf(file, "\n");
    fprintf(file, "#endif\n");
}

int main(int argc, char **argv) {
    char header_guard[256] = {0};
    if (argc != 2
        || !strrchr(argv[1], '.')
        || strlen(argv[1]) + 3 > sizeof(header_guard)) {
        printf("usage: keywordgen.c [output header file]\n");
        return 0;
    }
    sprintf(header_guard, "_%s_", strrchr(argv[1], '/') ? strrchr(argv[1], '/')+1 : argv[1]);
    *strrchr(header_guard, '.') = '_';

    keywords_init();
    
    for (int i = 0; i < arrsz(keyword_strs); i++) {
        if (!keyword_strs[i]) continue;
        keywords_add((strview_t){
            .str = keyword_strs[i],
            .len = strlen(keyword_strs[i]),
        }, i);
    }

    int ncollisions = 0, max_psl = 0;
    int hash_collisions = 0;
    for (int i = 0; i < LEX_KEYWORDMAP_SIZE; i++) {
        ncollisions += !!keywords[i].psl;
        if (keywords[i].psl > max_psl) {
            max_psl = keywords[i].psl;
        }
        for (int j = 0; j < LEX_KEYWORDMAP_SIZE; j++) {
            if (i == j) continue;
#ifdef INC_STR
            if (!keywords[i].str.str) continue;
            if (!keywords[j].str.str) continue;
#else
            if (keywords[i].type == tok_eof) continue;
            if (keywords[j].type == tok_eof) continue;
#endif
            if (keywords[i].hash == keywords[j].hash) hash_collisions++;
        }
    }
    printf("number of collisions: %d\n", ncollisions);
    printf("maximum psl: %d\n", max_psl);
    printf("hash collisions: %d\n", hash_collisions);
    
    FILE *file = fopen(argv[1], "w");
    if (!file) return -1;
    keywords_write(header_guard, ncollisions, max_psl, file);
    fclose(file);
    printf("keyword file written to: \"%s\"\n", argv[1]);

    return 0;
}

