#ifndef _keywords_h_
#define _keywords_h_

#include <stddef.h>

#include "lexer.h"

#define KEYWORDMAP_SIZE 83

// 
// Auto generated by keywordgen.
// This robinhood hashmap is used by the lexer to identify keywords.
// # of collisions: 10, max_psl: 2
// capacity: 40/83
// 
static const lex_keyword_t keywordmap[KEYWORDMAP_SIZE] = {
    (lex_keyword_t){
        .type = tok_false,
        .hash = 3607357620,
        .psl = 0,
    },
    (lex_keyword_t){
        .type = tok_i64,
        .hash = 4278599620,
        .psl = 0,
    },
    (lex_keyword_t){
        .type = tok_case,
        .hash = 1112193362,
        .psl = 0,
    },
    (lex_keyword_t){
        .type = tok_u64,
        .hash = 50742800,
        .psl = 0,
    },
    (lex_keyword_t){
        .type = tok_u8,
        .hash = 4028158992,
        .psl = 0,
    },
    (lex_keyword_t){
        .type = tok_if,
        .hash = 3969920964,
        .psl = 0,
    },
    (lex_keyword_t){
        .type = tok_eof,
        .hash = 0,
        .psl = 0,
    },
    (lex_keyword_t){
        .type = tok_eof,
        .hash = 0,
        .psl = 0,
    },
    (lex_keyword_t){
        .type = tok_sizeof,
        .hash = 393955607,
        .psl = 0,
    },
    (lex_keyword_t){
        .type = tok_i8,
        .hash = 3961048516,
        .psl = 1,
    },
    (lex_keyword_t){
        .type = tok_f64,
        .hash = 4127601049,
        .psl = 0,
    },
    (lex_keyword_t){
        .type = tok_eof,
        .hash = 0,
        .psl = 0,
    },
    (lex_keyword_t){
        .type = tok_alloc,
        .hash = 4257446749,
        .psl = 0,
    },
    (lex_keyword_t){
        .type = tok_break,
        .hash = 2156288138,
        .psl = 0,
    },
    (lex_keyword_t){
        .type = tok_b8,
        .hash = 3877160421,
        .psl = 1,
    },
    (lex_keyword_t){
        .type = tok_c8,
        .hash = 3860382802,
        .psl = 1,
    },
    (lex_keyword_t){
        .type = tok_eof,
        .hash = 0,
        .psl = 0,
    },
    (lex_keyword_t){
        .type = tok_eof,
        .hash = 0,
        .psl = 0,
    },
    (lex_keyword_t){
        .type = tok_eof,
        .hash = 0,
        .psl = 0,
    },
    (lex_keyword_t){
        .type = tok_eof,
        .hash = 0,
        .psl = 0,
    },
    (lex_keyword_t){
        .type = tok_eof,
        .hash = 0,
        .psl = 0,
    },
    (lex_keyword_t){
        .type = tok_typedef,
        .hash = 794910277,
        .psl = 0,
    },
    (lex_keyword_t){
        .type = tok_fn,
        .hash = 3818097049,
        .psl = 0,
    },
    (lex_keyword_t){
        .type = tok_eof,
        .hash = 0,
        .psl = 0,
    },
    (lex_keyword_t){
        .type = tok_eof,
        .hash = 0,
        .psl = 0,
    },
    (lex_keyword_t){
        .type = tok_do,
        .hash = 3784438643,
        .psl = 0,
    },
    (lex_keyword_t){
        .type = tok_eof,
        .hash = 0,
        .psl = 0,
    },
    (lex_keyword_t){
        .type = tok_eof,
        .hash = 0,
        .psl = 0,
    },
    (lex_keyword_t){
        .type = tok_eof,
        .hash = 0,
        .psl = 0,
    },
    (lex_keyword_t){
        .type = tok_eof,
        .hash = 0,
        .psl = 0,
    },
    (lex_keyword_t){
        .type = tok_eof,
        .hash = 0,
        .psl = 0,
    },
    (lex_keyword_t){
        .type = tok_free,
        .hash = 1324629401,
        .psl = 0,
    },
    (lex_keyword_t){
        .type = tok_switch,
        .hash = 385932851,
        .psl = 0,
    },
    (lex_keyword_t){
        .type = tok_eof,
        .hash = 0,
        .psl = 0,
    },
    (lex_keyword_t){
        .type = tok_eof,
        .hash = 0,
        .psl = 0,
    },
    (lex_keyword_t){
        .type = tok_eof,
        .hash = 0,
        .psl = 0,
    },
    (lex_keyword_t){
        .type = tok_for,
        .hash = 1688729241,
        .psl = 0,
    },
    (lex_keyword_t){
        .type = tok_eof,
        .hash = 0,
        .psl = 0,
    },
    (lex_keyword_t){
        .type = tok_eof,
        .hash = 0,
        .psl = 0,
    },
    (lex_keyword_t){
        .type = tok_eof,
        .hash = 0,
        .psl = 0,
    },
    (lex_keyword_t){
        .type = tok_static,
        .hash = 4057772017,
        .psl = 0,
    },
    (lex_keyword_t){
        .type = tok_return,
        .hash = 3013063717,
        .psl = 0,
    },
    (lex_keyword_t){
        .type = tok_u32,
        .hash = 209518352,
        .psl = 1,
    },
    (lex_keyword_t){
        .type = tok_eof,
        .hash = 0,
        .psl = 0,
    },
    (lex_keyword_t){
        .type = tok_eof,
        .hash = 0,
        .psl = 0,
    },
    (lex_keyword_t){
        .type = tok_i32,
        .hash = 142407876,
        .psl = 0,
    },
    (lex_keyword_t){
        .type = tok_true,
        .hash = 1136939939,
        .psl = 0,
    },
    (lex_keyword_t){
        .type = tok_eof,
        .hash = 0,
        .psl = 0,
    },
    (lex_keyword_t){
        .type = tok_f32,
        .hash = 4286376601,
        .psl = 0,
    },
    (lex_keyword_t){
        .type = tok_eof,
        .hash = 0,
        .psl = 0,
    },
    (lex_keyword_t){
        .type = tok_struct,
        .hash = 1389594931,
        .psl = 0,
    },
    (lex_keyword_t){
        .type = tok_c32,
        .hash = 41742162,
        .psl = 0,
    },
    (lex_keyword_t){
        .type = tok_eof,
        .hash = 0,
        .psl = 0,
    },
    (lex_keyword_t){
        .type = tok_eof,
        .hash = 0,
        .psl = 0,
    },
    (lex_keyword_t){
        .type = tok_eof,
        .hash = 0,
        .psl = 0,
    },
    (lex_keyword_t){
        .type = tok_eof,
        .hash = 0,
        .psl = 0,
    },
    (lex_keyword_t){
        .type = tok_eof,
        .hash = 0,
        .psl = 0,
    },
    (lex_keyword_t){
        .type = tok_eof,
        .hash = 0,
        .psl = 0,
    },
    (lex_keyword_t){
        .type = tok_eof,
        .hash = 0,
        .psl = 0,
    },
    (lex_keyword_t){
        .type = tok_eof,
        .hash = 0,
        .psl = 0,
    },
    (lex_keyword_t){
        .type = tok_eof,
        .hash = 0,
        .psl = 0,
    },
    (lex_keyword_t){
        .type = tok_eof,
        .hash = 0,
        .psl = 0,
    },
    (lex_keyword_t){
        .type = tok_eof,
        .hash = 0,
        .psl = 0,
    },
    (lex_keyword_t){
        .type = tok_eof,
        .hash = 0,
        .psl = 0,
    },
    (lex_keyword_t){
        .type = tok_eof,
        .hash = 0,
        .psl = 0,
    },
    (lex_keyword_t){
        .type = tok_lenof,
        .hash = 16458135,
        .psl = 0,
    },
    (lex_keyword_t){
        .type = tok_let,
        .hash = 1631547915,
        .psl = 0,
    },
    (lex_keyword_t){
        .type = tok_continue,
        .hash = 316468193,
        .psl = 1,
    },
    (lex_keyword_t){
        .type = tok_while,
        .hash = 282904489,
        .psl = 0,
    },
    (lex_keyword_t){
        .type = tok_null,
        .hash = 1941849393,
        .psl = 1,
    },
    (lex_keyword_t){
        .type = tok_eof,
        .hash = 0,
        .psl = 0,
    },
    (lex_keyword_t){
        .type = tok_extern,
        .hash = 3910361558,
        .psl = 0,
    },
    (lex_keyword_t){
        .type = tok_enum,
        .hash = 3402269920,
        .psl = 1,
    },
    (lex_keyword_t){
        .type = tok_u16,
        .hash = 103667984,
        .psl = 2,
    },
    (lex_keyword_t){
        .type = tok_eof,
        .hash = 0,
        .psl = 0,
    },
    (lex_keyword_t){
        .type = tok_i16,
        .hash = 36557508,
        .psl = 0,
    },
    (lex_keyword_t){
        .type = tok_c16,
        .hash = 4230859090,
        .psl = 1,
    },
    (lex_keyword_t){
        .type = tok_eof,
        .hash = 0,
        .psl = 0,
    },
    (lex_keyword_t){
        .type = tok_eof,
        .hash = 0,
        .psl = 0,
    },
    (lex_keyword_t){
        .type = tok_default,
        .hash = 2386637938,
        .psl = 0,
    },
    (lex_keyword_t){
        .type = tok_u0,
        .hash = 4028984336,
        .psl = 1,
    },
    (lex_keyword_t){
        .type = tok_const,
        .hash = 2517916882,
        .psl = 0,
    },
    (lex_keyword_t){
        .type = tok_eof,
        .hash = 0,
        .psl = 0,
    },
};

#endif
