#include <ctype.h>
#include <stdio.h>
#include <string.h>

#include "lexer.h"

// Auto generated by hashmapgen.c
static const keyword_t _keywords[128] = {
    (keyword_t){ .hash = 0, .len = 0, .psl = 0, .ty = tok_error, .str = NULL },
    (keyword_t){ .hash = 0, .len = 0, .psl = 0, .ty = tok_error, .str = NULL },
    (keyword_t){ .hash = 0, .len = 0, .psl = 0, .ty = tok_error, .str = NULL },
    (keyword_t){ .hash = 0, .len = 0, .psl = 0, .ty = tok_error, .str = NULL },
    (keyword_t){ .hash = 0, .len = 0, .psl = 0, .ty = tok_error, .str = NULL },
    (keyword_t){ .hash = 0, .len = 0, .psl = 0, .ty = tok_error, .str = NULL },
    (keyword_t){ .hash = 12294, .len = 5, .psl = 0, .ty = tok_break, .str = "break" },
    (keyword_t){ .hash = 0, .len = 0, .psl = 0, .ty = tok_error, .str = NULL },
    (keyword_t){ .hash = 0, .len = 0, .psl = 0, .ty = tok_error, .str = NULL },
    (keyword_t){ .hash = 0, .len = 0, .psl = 0, .ty = tok_error, .str = NULL },
    (keyword_t){ .hash = 0, .len = 0, .psl = 0, .ty = tok_error, .str = NULL },
    (keyword_t){ .hash = 12299, .len = 4, .psl = 0, .ty = tok_char, .str = "char" },
    (keyword_t){ .hash = 0, .len = 0, .psl = 0, .ty = tok_error, .str = NULL },
    (keyword_t){ .hash = 0, .len = 0, .psl = 0, .ty = tok_error, .str = NULL },
    (keyword_t){ .hash = 0, .len = 0, .psl = 0, .ty = tok_error, .str = NULL },
    (keyword_t){ .hash = 0, .len = 0, .psl = 0, .ty = tok_error, .str = NULL },
    (keyword_t){ .hash = 0, .len = 0, .psl = 0, .ty = tok_error, .str = NULL },
    (keyword_t){ .hash = 0, .len = 0, .psl = 0, .ty = tok_error, .str = NULL },
    (keyword_t){ .hash = 18194, .len = 6, .psl = 0, .ty = tok_static, .str = "static" },
    (keyword_t){ .hash = 16147, .len = 8, .psl = 0, .ty = tok_continue, .str = "continue" },
    (keyword_t){ .hash = 0, .len = 0, .psl = 0, .ty = tok_error, .str = NULL },
    (keyword_t){ .hash = 0, .len = 0, .psl = 0, .ty = tok_error, .str = NULL },
    (keyword_t){ .hash = 0, .len = 0, .psl = 0, .ty = tok_error, .str = NULL },
    (keyword_t){ .hash = 0, .len = 0, .psl = 0, .ty = tok_error, .str = NULL },
    (keyword_t){ .hash = 15640, .len = 4, .psl = 0, .ty = tok_goto, .str = "goto" },
    (keyword_t){ .hash = 0, .len = 0, .psl = 0, .ty = tok_error, .str = NULL },
    (keyword_t){ .hash = 0, .len = 0, .psl = 0, .ty = tok_error, .str = NULL },
    (keyword_t){ .hash = 16155, .len = 4, .psl = 0, .ty = tok_case, .str = "case" },
    (keyword_t){ .hash = 0, .len = 0, .psl = 0, .ty = tok_error, .str = NULL },
    (keyword_t){ .hash = 0, .len = 0, .psl = 0, .ty = tok_error, .str = NULL },
    (keyword_t){ .hash = 12318, .len = 4, .psl = 0, .ty = tok_bool, .str = "bool" },
    (keyword_t){ .hash = 0, .len = 0, .psl = 0, .ty = tok_error, .str = NULL },
    (keyword_t){ .hash = 17440, .len = 4, .psl = 0, .ty = tok_void, .str = "void" },
    (keyword_t){ .hash = 0, .len = 0, .psl = 0, .ty = tok_error, .str = NULL },
    (keyword_t){ .hash = 13218, .len = 3, .psl = 0, .ty = tok_int, .str = "int" },
    (keyword_t){ .hash = 0, .len = 0, .psl = 0, .ty = tok_error, .str = NULL },
    (keyword_t){ .hash = 0, .len = 0, .psl = 0, .ty = tok_error, .str = NULL },
    (keyword_t){ .hash = 17573, .len = 5, .psl = 0, .ty = tok_while, .str = "while" },
    (keyword_t){ .hash = 0, .len = 0, .psl = 0, .ty = tok_error, .str = NULL },
    (keyword_t){ .hash = 0, .len = 0, .psl = 0, .ty = tok_error, .str = NULL },
    (keyword_t){ .hash = 0, .len = 0, .psl = 0, .ty = tok_error, .str = NULL },
    (keyword_t){ .hash = 0, .len = 0, .psl = 0, .ty = tok_error, .str = NULL },
    (keyword_t){ .hash = 0, .len = 0, .psl = 0, .ty = tok_error, .str = NULL },
    (keyword_t){ .hash = 0, .len = 0, .psl = 0, .ty = tok_error, .str = NULL },
    (keyword_t){ .hash = 0, .len = 0, .psl = 0, .ty = tok_error, .str = NULL },
    (keyword_t){ .hash = 15533, .len = 2, .psl = 0, .ty = tok_if, .str = "if" },
    (keyword_t){ .hash = 0, .len = 0, .psl = 0, .ty = tok_error, .str = NULL },
    (keyword_t){ .hash = 0, .len = 0, .psl = 0, .ty = tok_error, .str = NULL },
    (keyword_t){ .hash = 12336, .len = 5, .psl = 0, .ty = tok_const, .str = "const" },
    (keyword_t){ .hash = 17456, .len = 8, .psl = 1, .ty = tok_volatile, .str = "volatile" },
    (keyword_t){ .hash = 0, .len = 0, .psl = 0, .ty = tok_error, .str = NULL },
    (keyword_t){ .hash = 0, .len = 0, .psl = 0, .ty = tok_error, .str = NULL },
    (keyword_t){ .hash = 18100, .len = 6, .psl = 0, .ty = tok_switch, .str = "switch" },
    (keyword_t){ .hash = 0, .len = 0, .psl = 0, .ty = tok_error, .str = NULL },
    (keyword_t){ .hash = 0, .len = 0, .psl = 0, .ty = tok_error, .str = NULL },
    (keyword_t){ .hash = 0, .len = 0, .psl = 0, .ty = tok_error, .str = NULL },
    (keyword_t){ .hash = 0, .len = 0, .psl = 0, .ty = tok_error, .str = NULL },
    (keyword_t){ .hash = 0, .len = 0, .psl = 0, .ty = tok_error, .str = NULL },
    (keyword_t){ .hash = 0, .len = 0, .psl = 0, .ty = tok_error, .str = NULL },
    (keyword_t){ .hash = 0, .len = 0, .psl = 0, .ty = tok_error, .str = NULL },
    (keyword_t){ .hash = 0, .len = 0, .psl = 0, .ty = tok_error, .str = NULL },
    (keyword_t){ .hash = 0, .len = 0, .psl = 0, .ty = tok_error, .str = NULL },
    (keyword_t){ .hash = 16062, .len = 2, .psl = 0, .ty = tok_do, .str = "do" },
    (keyword_t){ .hash = 0, .len = 0, .psl = 0, .ty = tok_error, .str = NULL },
    (keyword_t){ .hash = 15040, .len = 4, .psl = 0, .ty = tok_long, .str = "long" },
    (keyword_t){ .hash = 15681, .len = 5, .psl = 0, .ty = tok_false, .str = "false" },
    (keyword_t){ .hash = 0, .len = 0, .psl = 0, .ty = tok_error, .str = NULL },
    (keyword_t){ .hash = 0, .len = 0, .psl = 0, .ty = tok_error, .str = NULL },
    (keyword_t){ .hash = 12868, .len = 3, .psl = 0, .ty = tok_for, .str = "for" },
    (keyword_t){ .hash = 0, .len = 0, .psl = 0, .ty = tok_error, .str = NULL },
    (keyword_t){ .hash = 0, .len = 0, .psl = 0, .ty = tok_error, .str = NULL },
    (keyword_t){ .hash = 0, .len = 0, .psl = 0, .ty = tok_error, .str = NULL },
    (keyword_t){ .hash = 18888, .len = 13, .psl = 0, .ty = tok_static_assert, .str = "static_assert" },
    (keyword_t){ .hash = 0, .len = 0, .psl = 0, .ty = tok_error, .str = NULL },
    (keyword_t){ .hash = 0, .len = 0, .psl = 0, .ty = tok_error, .str = NULL },
    (keyword_t){ .hash = 14027, .len = 7, .psl = 0, .ty = tok_nullptr, .str = "nullptr" },
    (keyword_t){ .hash = 0, .len = 0, .psl = 0, .ty = tok_error, .str = NULL },
    (keyword_t){ .hash = 0, .len = 0, .psl = 0, .ty = tok_error, .str = NULL },
    (keyword_t){ .hash = 0, .len = 0, .psl = 0, .ty = tok_error, .str = NULL },
    (keyword_t){ .hash = 0, .len = 0, .psl = 0, .ty = tok_error, .str = NULL },
    (keyword_t){ .hash = 17744, .len = 4, .psl = 0, .ty = tok_true, .str = "true" },
    (keyword_t){ .hash = 0, .len = 0, .psl = 0, .ty = tok_error, .str = NULL },
    (keyword_t){ .hash = 0, .len = 0, .psl = 0, .ty = tok_error, .str = NULL },
    (keyword_t){ .hash = 17875, .len = 8, .psl = 0, .ty = tok_unsigned, .str = "unsigned" },
    (keyword_t){ .hash = 18900, .len = 5, .psl = 0, .ty = tok_short, .str = "short" },
    (keyword_t){ .hash = 0, .len = 0, .psl = 0, .ty = tok_error, .str = NULL },
    (keyword_t){ .hash = 15958, .len = 4, .psl = 0, .ty = tok_enum, .str = "enum" },
    (keyword_t){ .hash = 0, .len = 0, .psl = 0, .ty = tok_error, .str = NULL },
    (keyword_t){ .hash = 18776, .len = 8, .psl = 0, .ty = tok_restrict, .str = "restrict" },
    (keyword_t){ .hash = 18137, .len = 6, .psl = 0, .ty = tok_return, .str = "return" },
    (keyword_t){ .hash = 15962, .len = 6, .psl = 0, .ty = tok_extern, .str = "extern" },
    (keyword_t){ .hash = 18907, .len = 6, .psl = 0, .ty = tok_struct, .str = "struct" },
    (keyword_t){ .hash = 18140, .len = 6, .psl = 0, .ty = tok_sizeof, .str = "sizeof" },
    (keyword_t){ .hash = 12637, .len = 7, .psl = 0, .ty = tok_default, .str = "default" },
    (keyword_t){ .hash = 0, .len = 0, .psl = 0, .ty = tok_error, .str = NULL },
    (keyword_t){ .hash = 0, .len = 0, .psl = 0, .ty = tok_error, .str = NULL },
    (keyword_t){ .hash = 0, .len = 0, .psl = 0, .ty = tok_error, .str = NULL },
    (keyword_t){ .hash = 0, .len = 0, .psl = 0, .ty = tok_error, .str = NULL },
    (keyword_t){ .hash = 0, .len = 0, .psl = 0, .ty = tok_error, .str = NULL },
    (keyword_t){ .hash = 0, .len = 0, .psl = 0, .ty = tok_error, .str = NULL },
    (keyword_t){ .hash = 0, .len = 0, .psl = 0, .ty = tok_error, .str = NULL },
    (keyword_t){ .hash = 0, .len = 0, .psl = 0, .ty = tok_error, .str = NULL },
    (keyword_t){ .hash = 0, .len = 0, .psl = 0, .ty = tok_error, .str = NULL },
    (keyword_t){ .hash = 0, .len = 0, .psl = 0, .ty = tok_error, .str = NULL },
    (keyword_t){ .hash = 0, .len = 0, .psl = 0, .ty = tok_error, .str = NULL },
    (keyword_t){ .hash = 0, .len = 0, .psl = 0, .ty = tok_error, .str = NULL },
    (keyword_t){ .hash = 0, .len = 0, .psl = 0, .ty = tok_error, .str = NULL },
    (keyword_t){ .hash = 0, .len = 0, .psl = 0, .ty = tok_error, .str = NULL },
    (keyword_t){ .hash = 0, .len = 0, .psl = 0, .ty = tok_error, .str = NULL },
    (keyword_t){ .hash = 0, .len = 0, .psl = 0, .ty = tok_error, .str = NULL },
    (keyword_t){ .hash = 12526, .len = 4, .psl = 0, .ty = tok_auto, .str = "auto" },
    (keyword_t){ .hash = 17775, .len = 5, .psl = 0, .ty = tok_union, .str = "union" },
    (keyword_t){ .hash = 0, .len = 0, .psl = 0, .ty = tok_error, .str = NULL },
    (keyword_t){ .hash = 0, .len = 0, .psl = 0, .ty = tok_error, .str = NULL },
    (keyword_t){ .hash = 17778, .len = 6, .psl = 0, .ty = tok_typeof, .str = "typeof" },
    (keyword_t){ .hash = 0, .len = 0, .psl = 0, .ty = tok_error, .str = NULL },
    (keyword_t){ .hash = 15988, .len = 6, .psl = 0, .ty = tok_double, .str = "double" },
    (keyword_t){ .hash = 0, .len = 0, .psl = 0, .ty = tok_error, .str = NULL },
    (keyword_t){ .hash = 0, .len = 0, .psl = 0, .ty = tok_error, .str = NULL },
    (keyword_t){ .hash = 0, .len = 0, .psl = 0, .ty = tok_error, .str = NULL },
    (keyword_t){ .hash = 18168, .len = 6, .psl = 0, .ty = tok_signed, .str = "signed" },
    (keyword_t){ .hash = 0, .len = 0, .psl = 0, .ty = tok_error, .str = NULL },
    (keyword_t){ .hash = 16122, .len = 4, .psl = 0, .ty = tok_else, .str = "else" },
    (keyword_t){ .hash = 12923, .len = 5, .psl = 0, .ty = tok_float, .str = "float" },
    (keyword_t){ .hash = 17788, .len = 7, .psl = 0, .ty = tok_typedef, .str = "typedef" },
    (keyword_t){ .hash = 0, .len = 0, .psl = 0, .ty = tok_error, .str = NULL },
    (keyword_t){ .hash = 0, .len = 0, .psl = 0, .ty = tok_error, .str = NULL },
    (keyword_t){ .hash = 0, .len = 0, .psl = 0, .ty = tok_error, .str = NULL },
};

static tok_t getkeyword(const lexer_t *const state, const char *const keyword, size_t len) {
	const uint32_t hash = ident_hash(keyword, len);
	int i = hash % arrlen(_keywords), psl = 0;
	while (psl <= _keywords[i].psl) {
		if (_keywords[i].hash == hash && strncmp(_keywords[i].str, keyword, len) == 0) {
			return (tok_t){
				.ty = _keywords[i].ty,
				.lit = keyword,
				.len = len,
				.line = state->line,
				.chr = state->chr,
			};
		}

		psl++;
		i = (i + 1) % arrlen(_keywords);
	}

	return (tok_t){
		.ty = tok_ident,
		.lit = keyword,
		.len = len,
		.line = state->line,
		.chr = state->chr,
	};
}

inline static void consume_line(lexer_t *const state) {
	while (*(state->head++) != '\n');
	state->head_line++;
	state->head_chr = 1;
}
inline static bool consume_whitespace(lexer_t *const state) {
	bool line_start = state->chr == 1;
	while (isspace(*state->head) || *state->head == '/' || *state->head == '#') {
		char head = *(state->head++);
		if (head == '/' && *state->head == '/') consume_line(state);
		else if (head == '/') return true;
		if (head == '#') {
			if (line_start) consume_line(state);
			else return false;
		}
		state->head_chr++;
		if (head == '\n') {
			line_start = true;
			state->head_line++;
			state->head_chr = 1;
		}
	}

	return true;
}
static tok_t consume_ident(lexer_t *const state) {
	const char *keyword = state->head;
	size_t len = 0;
	while (isalnum(*state->head) || *state->head == '_') {
		len++;
		state->head++;
		state->head_chr++;
		if (*state->head == '\0') return make_errtok(state, err_unexpected, "EOF");
	}
	return getkeyword(state, keyword, len);
}
static tok_t consume_string(lexer_t *const state) {
	tok_t tok = (tok_t){ .ty = tok_string, .lit = state->head, .len = 0, .line = state->line, .chr = state->chr };
	do {
		state->head++;
		state->head_chr++;
		tok.len++;
		if (*state->head == '\0') return make_errtok(state, err_unexpected, "EOF");
		if (*state->head == '\n') return make_errtok(state, err_unexpected, "EOF");
	} while (*state->head != '\"');
	state->head++;
	state->head_chr++;
	tok.len++;
	return tok;
}
static tok_t consume_number(lexer_t *const state) {
	tok_t tok = (tok_t){ .ty = tok_integer, .lit = state->head, .len = 0, .line = state->line, .chr = state->chr };
	while (isdigit(*state->head) || *state->head == '.'
		|| *state->head == 'x' || *state->head == 'b'
		|| *state->head == 'X' || *state->head == 'e') {
		if (*state->head == '.') tok.ty = tok_floating;
		state->head++;
		tok.len++;
	}
	if (*state->head == '\0') return make_errtok(state, err_unexpected, "EOF");
	if (isalpha(*state->head)) {
		const char c = *state->head;
		if (c != 'u' && c != 'l' && c != 'U' && c != 'L') return make_errtok(state, err_expected, "'u' or 'l'");
		state->head++;
		state->head_chr++;
		tok.len++;
		if ((c == 'l' || c == 'L' || c == 'u' || c == 'U') && (*state->head == 'l' || *state->head == 'L')) {
			state->head++;
			state->head_chr++;
			tok.len++;
		}
	}
	return tok;
}

static tok_t _lexer_nexttok(lexer_t *const state) {
	if (!consume_whitespace(state)) return make_errtok(state, err_unexpected, "");
	state->line = state->head_line;
	state->chr = state->head_chr;
	const char *const c = state->head++;
	state->head_chr++;
	switch (*c) {
	case '\0': return (tok_t){ .ty = tok_eof, .lit = c, .len = 1, .line = state->line, .chr = state->chr };
	case '+':
		if (*state->head == '+') {
			state->head++;
			state->head_chr++;
			return (tok_t){ .ty = tok_plusplus, .lit = c, .len = 2, .line = state->line, .chr = state->chr };
		} else if (*state->head == '=') {
			state->head++;
			state->head_chr++;
			return (tok_t){ .ty = tok_pluseq, .lit = c, .len = 2, .line = state->line, .chr = state->chr };
		} else {
			return (tok_t){ .ty = tok_plus, .lit = c, .len = 1, .line = state->line, .chr = state->chr };
		}
	case '-':
		if (*state->head == '-') {
			state->head++;
			state->head_chr++;
			return (tok_t){ .ty = tok_minusminus, .lit = c, .len = 2, .line = state->line, .chr = state->chr };
		} else if (*state->head == '>') {
			state->head++;
			state->head_chr++;
			return (tok_t){ .ty = tok_arrow, .lit = c, .len = 2, .line = state->line, .chr = state->chr };
		} else if (*state->head == '=') {
			state->head++;
			state->head_chr++;
			return (tok_t){ .ty = tok_minuseq, .lit = c, .len = 2, .line = state->line, .chr = state->chr };
		} else {
			return (tok_t){ .ty = tok_minus, .lit = c, .len = 1, .line = state->line, .chr = state->chr };
		}
	case '=':
		if (*state->head == '=') {
			state->head++;
			state->head_chr++;
			return (tok_t){ .ty = tok_eqeq, .lit = c, .len = 2, .line = state->line, .chr = state->chr };
		} else {
			return (tok_t){ .ty = tok_eq, .lit = c, .len = 1, .line = state->line, .chr = state->chr };
		}
	case '&':
		if (*state->head == '=') {
			state->head++;
			state->head_chr++;
			return (tok_t){ .ty = tok_bitandeq, .lit = c, .len = 2, .line = state->line, .chr = state->chr };
		} else if (*state->head == '&') {
			state->head++;
			state->head_chr++;
			return (tok_t){ .ty = tok_and, .lit = c, .len = 2, .line = state->line, .chr = state->chr };
		} else {
			return (tok_t){ .ty = tok_bitand, .lit = c, .len = 1, .line = state->line, .chr = state->chr };
		}
	case '|':
		if (*state->head == '=') {
			state->head++;
			state->head_chr++;
			return (tok_t){ .ty = tok_bitoreq, .lit = c, .len = 2, .line = state->line, .chr = state->chr };
		} else if (*state->head == '|') {
			state->head++;
			state->head_chr++;
			return (tok_t){ .ty = tok_or, .lit = c, .len = 2, .line = state->line, .chr = state->chr };
		} else {
			return (tok_t){ .ty = tok_bitor, .lit = c, .len = 1, .line = state->line, .chr = state->chr };
		}
	case '!':
		if (*state->head == '=') {
			state->head++;
			state->head_chr++;
			return (tok_t){ .ty = tok_noteq, .lit = c, .len = 2, .line = state->line, .chr = state->chr };
		} else {
			return (tok_t){ .ty = tok_not, .lit = c, .len = 1, .line = state->line, .chr = state->chr };
		}
	case '>':
		if (*state->head == '=') {
			state->head++;
			state->head_chr++;
			return (tok_t){ .ty = tok_ge, .lit = c, .len = 2, .line = state->line, .chr = state->chr };
		} if (*state->head == '>') {
			state->head++;
			state->head_chr++;
			if (*state->head == '=') {
				state->head++;
				state->head_chr++;
				return (tok_t){ .ty = tok_shreq, .lit = c, .len = 3, .line = state->line, .chr = state->chr };
			} else {
				return (tok_t){ .ty = tok_shr, .lit = c, .len = 2, .line = state->line, .chr = state->chr };
			}
		} else {
			return (tok_t){ .ty = tok_gt, .lit = c, .len = 1, .line = state->line, .chr = state->chr };
		}
	case '<':
		if (*state->head == '=') {
			state->head++;
			state->head_chr++;
			return (tok_t){ .ty = tok_le, .lit = c, .len = 2, .line = state->line, .chr = state->chr };
		} if (*state->head == '<') {
			state->head++;
			state->head_chr++;
			if (*state->head == '=') {
				state->head++;
				state->head_chr++;
				return (tok_t){ .ty = tok_shleq, .lit = c, .len = 3, .line = state->line, .chr = state->chr };
			} else {
				return (tok_t){ .ty = tok_shl, .lit = c, .len = 2, .line = state->line, .chr = state->chr };
			}
		} else {
			return (tok_t){ .ty = tok_lt, .lit = c, .len = 1, .line = state->line, .chr = state->chr };
		}
	case '~': return (tok_t){ .ty = tok_bitnot, .lit = c, .len = 1, .line = state->line, .chr = state->chr };
	case '^':
		if (*state->head == '=') {
			state->head++;
			state->head_chr++;
			return (tok_t){ .ty = tok_xoreq, .lit = c, .len = 2, .line = state->line, .chr = state->chr };
		} else {
			return (tok_t){ .ty = tok_xor, .lit = c, .len = 1, .line = state->line, .chr = state->chr };
		}
	case '(': return (tok_t){ .ty = tok_lparen, .lit = c, .len = 1, .line = state->line, .chr = state->chr };
	case ')': return (tok_t){ .ty = tok_rparen, .lit = c, .len = 1, .line = state->line, .chr = state->chr };
	case '[': return (tok_t){ .ty = tok_lbrack, .lit = c, .len = 1, .line = state->line, .chr = state->chr };
	case ']': return (tok_t){ .ty = tok_rbrack, .lit = c, .len = 1, .line = state->line, .chr = state->chr };
	case '{': return (tok_t){ .ty = tok_lbrace, .lit = c, .len = 1, .line = state->line, .chr = state->chr };
	case '}': return (tok_t){ .ty = tok_rbrace, .lit = c, .len = 1, .line = state->line, .chr = state->chr };
	case '*':
		if (*state->head == '=') {
			state->head++;
			state->head_chr++;
			return (tok_t){ .ty = tok_stareq, .lit = c, .len = 2, .line = state->line, .chr = state->chr };
		} else {
			return (tok_t){ .ty = tok_star, .lit = c, .len = 1, .line = state->line, .chr = state->chr };
		}
	case ',': return (tok_t){ .ty = tok_comma, .lit = c, .len = 1, .line = state->line, .chr = state->chr };
	case ';': return (tok_t){ .ty = tok_semicol, .lit = c, .len = 1, .line = state->line, .chr = state->chr };
	case '?': return (tok_t){ .ty = tok_qmark, .lit = c, .len = 1, .line = state->line, .chr = state->chr };
	case ':': return (tok_t){ .ty = tok_colon, .lit = c, .len = 1, .line = state->line, .chr = state->chr };
	case '/':
		if (*state->head == '=') {
			state->head++;
			state->head_chr++;
			return (tok_t){ .ty = tok_slasheq, .lit = c, .len = 2, .line = state->line, .chr = state->chr };
		} else {
			return (tok_t){ .ty = tok_slash, .lit = c, .len = 1, .line = state->line, .chr = state->chr };
		}
	case '%':
		if (*state->head == '=') {
			state->head++;
			state->head_chr++;
			return (tok_t){ .ty = tok_percenteq, .lit = c, .len = 2, .line = state->line, .chr = state->chr };
		} else {
			return (tok_t){ .ty = tok_percent, .lit = c, .len = 1, .line = state->line, .chr = state->chr };
		}
	case '\'':
		if (*state->head == '\\') {
			state->head += 3;
			state->head_chr += 3;
			if (*(state->head - 1) != '\'') return make_errtok(state, err_expected, "'");
			return (tok_t){ .ty = tok_char_lit, .lit = c, .len = 4, .line = state->line, .chr = state->chr };
		} else {
			state->head += 2;
			state->head_chr += 2;
			return (tok_t){ .ty = tok_char_lit, .lit = c, .len = 3, .line = state->line, .chr = state->chr };
		}
	case '.':
		if (isdigit(*state->head)) {
			state->head--;
			state->head_chr--;
			return consume_number(state);
		}
		return (tok_t){ .ty = tok_dot, .lit = c, .len = 1, .line = state->line, .chr = state->chr };
	case '0': case '1': case '2': case '3': case '4':
	case '5': case '6': case '7': case '8': case '9':
		state->head--;
		state->head_chr--;
		return consume_number(state);
	case '"':
		state->head--;
		state->head_chr--;
		return consume_string(state);
	default:
		if (isalpha(*c)) {
			state->head--;
			state->head_chr--;
			return consume_ident(state);
		} else {
			return make_errtok(state, err_expected, "identifier");
		}
	}
}

bool lexer_next(lexer_t *const state) {
	memmove(state->toks, state->toks + 1, sizeof(state->toks) - sizeof(state->toks[0]));
	const tok_t *const last_tok = &state->toks[arrlen(state->toks) - 2];
	if (last_tok->ty != tok_error && last_tok->ty != tok_eof) {
		state->toks[arrlen(state->toks) - 1] = _lexer_nexttok(state);
	}
	return state->curr.ty != tok_eof && state->curr.ty != tok_error;
}

lexer_t lexer_init(const char *script) {
	lexer_t state = (lexer_t){
		.head = script,
		.chr = 1,
		.line = 1,
		.head_line = 1,
		.head_chr = 1,
		.curr = (tok_t){ .ty = tok_undefined },
	};
	state.prev = (tok_t){ .ty = tok_undefined };
	state.peek = _lexer_nexttok(&state);
	return state;
}

const char *tokty_to_str(const tokty_t ty) {
	switch (ty) {
#define enumdef(e) case e: return #e;
tokty_def
#undef enumdef
	default: return "ERR";
	}
}

void dbg_tok_print(const tok_t tok) {
	printf("%zu:%zu:%s, len: %zu\n", tok.line, tok.chr, tokty_to_str(tok.ty), tok.len);
}

